#!/usr/bin/env python

import sys
import argparse
from utils.PipelineUtils import DataUtils

parser = argparse.ArgumentParser()
grp = parser.add_mutually_exclusive_group(required=True)
grp.add_argument("--inputFile")
grp.add_argument("--analysisId")
parser.add_argument("--scalingFactor", required=False, default=1)
parser.add_argument("--roundToNearestGbInterval", required=False, default=50)
args = parser.parse_args()

if args.inputFile:
	print DataUtils.calculateDiskSize(inputFile=args.inputFile, scalingFactor=args.scalingFactor, roundToNearestGbInterval=args.roundToNearestGbInterval)
elif args.analysisId:
	print DataUtils.calculateDiskSize(analysisId=args.analysisId, scalingFactor=args.scalingFactor, roundToNearestGbInterval=args.roundToNearestGbInterval)
