#!/usr/bin/env python

import argparse
import requests
from utils.PipelineUtils import DataUtils

parser = argparse.ArgumentParser()
parser.add_argument("--analysisId", required=True)
args = parser.parse_args()
	
try:
	print DataUtils.getChecksum(args.analysisId)
except LookupError:
	print "ERROR: no files found for analysis ID {a}!".format(a=args.analysisId)
	exit(-1)
	
		

