#!/usr/bin/env python

import argparse
from pipelines.utils import DataUtils

parser = argparse.ArgumentParser()
parser.add_argument("--analysisId", required=True)
args = parser.parse_args()

files = DataUtils.getFilenames(args.analysisId)

if len(files) > 0:
	for f in files:
		print f
else:
	print "No files found!"