#!/usr/bin/env python
import argparse
from pipelines.config import PipelineConfig, PipelineConfigError

if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument("--projectId")

	args = parser.parse_args()

	try:
		c = PipelineConfig(projectId=args.projectId)

	except PipelineConfigError as e:
		print "ERROR: couldn't create config file: {reason}".format(reason=e)
		exit(-1)
