#!/usr/bin/env python
import pika
import argparse
from pipelines.utils import PipelinesConfig, PipelinesConfigUpdateHandler, PipelineSchedulerUtils, PipelineDbUtils

# NOTE: this process should be started up as part of the scheduling system (managed by Supervisor)

if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument("--config")
	args = parser.parse_args()

	config = PipelinesConfig(path=args.config)

	connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
	channel = connection.channel()
	channel.queue_declare(queue="WAITING")

	def callback(ch, method, properties, body):
		pass # do stuff

	channel.basic_consume(callback, queue='WAITING', no_ack=True)
	channel.start_consuming()






		



